from agency_swarm.tools import BaseTool
from pydantic import Field
import requests

class ReportSenderTool(BaseTool):
    """
    This tool passes the summary report generated by the RepositoryAnalyzerTool to the ContentCreator agent for further processing.
    It ensures that the report is correctly formatted and transmitted to the ContentCreator agent.
    """

    summary_report: str = Field(
        ..., description="The summary report generated by the RepositoryAnalyzerTool."
    )
    content_creator_endpoint: str = Field(
        ..., description="The endpoint URL of the ContentCreator agent."
    )

    def format_report(self):
        """
        Format the summary report to ensure it is correctly structured for transmission.
        """
        formatted_report = {
            "report": self.summary_report
        }
        return formatted_report

    def send_report(self, formatted_report):
        """
        Send the formatted report to the ContentCreator agent.
        """
        try:
            response = requests.post(self.content_creator_endpoint, json=formatted_report)
            response.raise_for_status()
            return "Report successfully sent to ContentCreator agent."
        except requests.exceptions.RequestException as e:
            return f"An error occurred during transmission: {e}"

    def run(self):
        """
        The implementation of the run method, where the tool's main functionality is executed.
        This method should utilize the fields defined above to perform the task.
        """
        try:
            formatted_report = self.format_report()
            result = self.send_report(formatted_report)
            return result
        except Exception as e:
            return f"An error occurred: {e}"

# Example usage:
# summary_report = "Repository Analysis Report\n===========================\n\nMain Directories:\n- src\n\nMain Files:\n- src/main.py\n- README.md\n- config.yaml\n\nKey Components:\n---------------\nMain Scripts:\n- src/main.py\n\nConfiguration Files:\n- config.yaml\n\nDocumentation:\n- README.md\n"
# content_creator_endpoint = "http://content-creator-agent/api/process_report"
# tool = ReportSenderTool(summary_report=summary_report, content_creator_endpoint=content_creator_endpoint)
# print(tool.run())